# Generated by Django 2.1.2 on 2018-12-09 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_name', models.CharField(db_index=True, max_length=200)),
                ('job_payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('job_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('progress_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('state', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Started'), ('3', 'Success'), ('4', 'Failure'), ('5', 'Retry'), ('6', 'Revoked')], db_index=True, default='1', max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
